### ISSUE TITLE
Tooltip Box is broken and icon would not be shown

### ISSUE THREAD

**Issue by Ley21** [viion/XIVDB-Tooltips#14]
Hello I'm again ^^

I build a page where I use the tooltips. My currently problem is that the tooltip box and the icon of the object is not visible correctly.

Link: http://minion.snsubs.de/?lang=en

Just try it. I use the js file from your repository so if you check something in it should be shown on the page.

Can you pls take a look on this issue.

**Comment by viion** [comment]
Hello!

It looks like you're linking the file from GitHub?

Can you include the file from http://xivdb.com/tooltips.js - You're not allowed to use GitHub as a CDN, and linking Javascript will cause issues: https://github.com/blog/1482-
