### ISSUE TITLE
After jquery ajax reenable tooltip in page

### ISSUE THREAD

**Issue by Ley21** [viion/XIVDB-Tooltips#15]
Hello I want to reenable the tooltips after modify content on page with ajax.
Is there any possiblity to do this.

For example:
On first call table with items is created and tooltips were loaded for this table.
After press an button table will recreate with other items over ajax. Now want to have tooltips again.

**Comment by viion** [comment]
Hey

You can call XIVDBTooltips.get to get them, if your Ajax is heavy then getDelayed might be smoother

**Comment by Ley21** [comment]
Thanks thats works.
