### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by DarkArtek** [viion/XIVDB-Tooltips#16]
Hello, i am using the tooltips from the first version but now i have a small problem. It load the tooltips.min.js but inside the chrome console i have: `Uncaught TypeError: $ is not a function` which it's preventing the tooltips to appear. The site's url is: http://finalfantasyxivitalia.it . Thanks.

**Comment by viion** [comment]
That is strange, your embed of JQuery doesn't assign to the `$` symbol, are you using that for something else? Or another script?

If not, placing
```js
var $ = jQuery;
```

In your head may fix this.

**Comment by DarkArtek** [comment]
I don't have any jQuery script (i have checked) I am using the one included inside the XIVSB's tooltips.

**Comment by viion** [comment]
Your theme does have jquery embedded, also has jquery migrate and other stuff, maybe plugins?

![jq](https://cloud.githubusercontent.com/assets/270800/18994690/e291e0ac-8720-11e6-9c02-e385ade36191.png)

**Comment by DarkArtek** [comment]
For placing your fix, i could use the script syntax? (`<script>var $= jQuery</script>`)

**Comment by viion** [comment]
yeah try that just before the tooltips embed, see if it fixes it.

**Comment by DarkArtek** [comment]
Worked like a charm. 

> Passed dependency check 0
> tooltips.js:1 requesting tooltips 0
> tooltips.js:1 links detected 769
> tooltips.js:1 processing links 770
> tooltips.js:1 completed data object 770
