### ISSUE TITLE
Load Problems in some forum (phpBB)

### ISSUE THREAD

**Issue by rob1337** [viion/XIVDB-Tooltips#4]
Loading Tooltip only in Mobile Browser after 3 reload.
No loading on Chrome Windows/Mac.
Missing declaration and space between operators and commands, Semicolons.(Because are not optional)
Forum Minimized it, but cleaning code helped me.

**Comment by viion** [comment]
Do you have a URL i can see?

**Comment by rob1337** [comment]
The forum? http://coilgroup-loading.forumieren.com/
script i changed http://coilgroup-loading.forumieren.com/10277.js

**Comment by rob1337** [comment]
initXIVDBTooltips = function () {..}; need a var initXIVDBTooltips declaration.
because without get unexpected identifier error
