### ISSUE TITLE
Spell Name to ID

### ISSUE THREAD

**Issue by philarr** [viion/XIVDB-Tooltips#5]
Is there a JSON file for the spell names as index to ID like http://xivpads.com/items.json

**Comment by viion** [comment]
Not exactly, you could create your own quite easily though.

Using this XML: http://xivdb.com/sitemap/?skill
And the code example here: https://github.com/viion/XIVPads-LodestoneAPI/issues/56#issuecomment-72365040

Change ``` items.json ``` to ``` skills.json ``` during the ``` file_put_contents() `` and you should get md5 hashed to id list.

**Comment by philarr** [comment]
Thanks I was able to generate the file! 
Is there a sitemap for status like Astral Fire etc. as well?

**Comment by viion** [comment]
Currently no, only: Achievements, Fates, Monsters, NPCs, Recipes, Skills and Items.

In the next few weeks XIVDB will be going through a bit transition and there will be an API that will provide everything.

**Comment by viion** [comment]
Closing this as there is now an API for this

https://api.xivdb.com/action
