### ISSUE TITLE
ID is empty with latest sitemap download

### ISSUE THREAD

**Issue by Drakonas** [viion/XIVDB-Tooltips#6]
I'm trying to create a Wordpress Snippet to create links non-dynamically, so that posters on the site can create their own fancy tooltip links. As such, most of my guild members will not know how to get the ID. Thus, using the sitemap XML seemed appropriate. Problem is, when I parse the XML, no ID is returned. Why is this?

http://ffxiv.3rdn3rd.com/hello-world/

My snippet: http://pastebin.com/6XVgbcAY

No errors show in the Apache logs or in Google Chrome, so I can't figure out what's wrong.

I did add the tooltip.js to the header.

**Comment by viion** [comment]
Hello!

Sitemap is just a bunch of URLs for Google.The code might be a bit out dated now, so one thing you could do is this.

I assume you're trying to get the XIVDB id from the item name?

```php
// get dump of hashed ID's
$xivdb = json_decode(file_get_contents('http://45.56.73.127/api/?type=item&name=all'), true);

// function to get real id from item name
function getItemId($string)
{
        global $xivdb;
        $string = trim(strip_tags(htmlspecialchars_decode(trim($string), ENT_QUOTES)));
        $string = strtolower($string);
        $string = preg_replace('/[^\w]/', null, $string);
        $string = sha1($string);

        if (isset($xivdb[$string])) {
                return $xivdb[$string];
        }
        
        return false;
}

$id = getItemId('X-Potion');
```


Alternatively, you could try something like this which fetches a lot of information:

```php
function getItemId($string)
{
        $string = urlencode($string);
        $data = file_get_contents('http://45.56.73.127/api/?type=item&name='. $string);
        return json_decode($data, true);
}

$item = getItemId('X-Potion');
$id = $item['id'];
```

The IP will change to xivdb.com in the next day or two as the server is moved.

That should get you at least something!

**Comment by Drakonas** [comment]
I take it only items and characters are implemented currently? Also, how does one use names of items with 2 words or more?

**Comment by viion** [comment]
Only items in this API version, it was just a mock up for my own use.

```urlencode``` will handle multiple words within an item.

```php
$name = 'Crown Of Light';
echo urlencode($name);
// Crown+Of+Light
```

http://45.56.73.127/api/?type=item&name=Crown+Of+Light

**Comment by Drakonas** [comment]
Should I expect the addition of other types of content within the next few weeks? Or will it probably be longer...

**Comment by viion** [comment]
Whenever I have time.
