### ISSUE TITLE
 http://xivpads.com/items.json file is down?

### ISSUE THREAD

**Issue by Exodus1028** [viion/XIVDB-Tooltips#7]
Hello!

first of all, thanks for your great work!

i tried downloading the item.json you kindly provided
the page, though, comes up empty

any chance you can reup this?
also, is there a way to provide an XML-alternative? i dont like json that much tbh :)

cheers
Daniel

**Comment by Exodus1028** [comment]
auhm, it seems its the same as querying 

http://ff14db.com/api/?type=item&name=all

right? :)

**Comment by viion** [comment]
Hello!

Yes you could use that with a hashed name, or you could parse http://xivdb.com/sitemap/

A more useful API will be built in the future which I will likely include xml as an option, though I prefer Json as its simplier XD
