### ISSUE TITLE
Undefined index: HTTP_REFERER

### ISSUE THREAD

**Issue by jingai** [viion/XIVDB-Tooltips#8]
Trying to add tooltips to my forum.  Getting the following:

```
Notice: Undefined index: HTTP_REFERER in /var/www/xivdb/site/modules/fpop/fpop.php on line 113
```

which is causing a JSON Parse error (Unrecognized token '<', due to the PHP error printed from fpop.php) in tooltips.js at line 121.

What do I need to do to correct this?

**Comment by viion** [comment]
I can fix this tonight, seems your server might be removing that from its environment, very weird.

Easy fix though but I'm at work right now!

**Comment by jingai** [comment]
Take your time, it's not a huge deal.  Thanks for looking into it!

I think it may have something to do with the fact that xivdb.com can't be reached over HTTPS anymore.  My site is HTTPS, and I think the default behavior is to remove HTTP_REFERER when transitioning between the two.

**Comment by viion** [comment]
It might be just that. Try it now and see if it works, removed that error!

**Comment by jingai** [comment]
Yup, working fine now.  Thanks!

**Comment by jingai** [comment]
Do you have any plans to provide xivdb.com over HTTPS again?  Because there is another issue now -- Chrome and Firefox really don't like to allow mixed content.  The tooltips don't work without the user having to manually provide an exception via a somewhat unintuitive (for most people) process.

**Comment by viion** [comment]
I'm curious what exception you're having to do? As far as im aware you would only get a warning regarding cross site scripting. Which I can probably just remove for that file on the XIVDB server.

I do want to get xivdb on https but it is unlikely to be soon as no major development is being done until the expansion pack is being released.

**Comment by jingai** [comment]
Firefox and Chrome by default now disallow mixed content (HTTP and HTTPS on one page).  The user has to explicitly allow this, and the browser has some scary language about it for those that don't understand it.

In Firefox, the shield pops up next to the URL bar.  If you click it, it warns about how the site contains mixed content and it is being blocked.  From the shield icon, it directs the user here:

https://support.mozilla.org/en-US/kb/how-does-content-isnt-secure-affect-my-safety?as=u&utm_source=inproduct

In Chrome, it's basically the same thing -- grey shield icon.  The user doesn't know immediately that they have to do anything about this though.

It's possible it won't complain if you do what you suggested.
